// <auto-generated />
using System;
using LeadManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LeadManager.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250427095132_AddJobEntityAndSeedData")]
    partial class AddJobEntityAndSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateRequested")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Yanderra 2574",
                            ClientName = "Bill Smith",
                            DateRequested = new DateTime(2024, 1, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Address = "Woolooware 2230",
                            ClientName = "Craig Johnson",
                            DateRequested = new DateTime(2024, 1, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Address = "Carramar 6031",
                            ClientName = "Pete Sample",
                            DateRequested = new DateTime(2024, 9, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            Address = "Sydney 2000",
                            ClientName = "Maria Garcia",
                            DateRequested = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            Address = "Quinns Rocks 6030",
                            ClientName = "Chris Sanderson",
                            DateRequested = new DateTime(2023, 8, 30, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("LeadManager.Models.Lead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("JobId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OriginalPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Suburb")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("Leads");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Painters",
                            DateCreated = new DateTime(2024, 1, 4, 14, 37, 0, 0, DateTimeKind.Utc),
                            Description = "Need to paint 2 aluminum windows and a sliding glass door",
                            Email = "bill@example.com",
                            FirstName = "Bill",
                            JobId = 1,
                            LastName = "Smith",
                            OriginalPrice = 62.00m,
                            Phone = "0412345678",
                            Price = 62.00m,
                            Status = 0,
                            Suburb = "Yanderra 2574"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Interior Painters",
                            DateCreated = new DateTime(2024, 1, 4, 13, 15, 0, 0, DateTimeKind.Utc),
                            Description = "Internal walls 3 colours",
                            Email = "craig@sample.net",
                            FirstName = "Craig",
                            JobId = 2,
                            LastName = "Johnson",
                            OriginalPrice = 49.00m,
                            Phone = "0498765432",
                            Price = 49.00m,
                            Status = 0,
                            Suburb = "Woolooware 2230"
                        },
                        new
                        {
                            Id = 3,
                            Category = "General Building Work",
                            DateCreated = new DateTime(2024, 9, 5, 10, 36, 0, 0, DateTimeKind.Utc),
                            Description = "Plaster exposed brick walls",
                            Email = "pete@mailinator.com",
                            FirstName = "Pete",
                            JobId = 3,
                            LastName = "Sample",
                            OriginalPrice = 526.00m,
                            Phone = "0412345678",
                            Price = 526.00m,
                            Status = 0,
                            Suburb = "Carramar 6031"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Electrical",
                            DateCreated = new DateTime(2024, 2, 15, 9, 20, 0, 0, DateTimeKind.Utc),
                            Description = "Install new lighting fixtures",
                            Email = "maria@example.com",
                            FirstName = "Maria",
                            JobId = 4,
                            LastName = "Garcia",
                            OriginalPrice = 850.00m,
                            Phone = "0422334455",
                            Price = 850.00m,
                            Status = 0,
                            Suburb = "Sydney 2000"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Home Renovations",
                            DateCreated = new DateTime(2023, 8, 30, 11, 14, 0, 0, DateTimeKind.Utc),
                            Description = "Two story building conversion",
                            Email = "another.fake@hipmail.com",
                            FirstName = "Chris",
                            JobId = 5,
                            LastName = "Sanderson",
                            OriginalPrice = 1532.00m,
                            Phone = "04987654321",
                            Price = 1532.00m,
                            Status = 1,
                            Suburb = "Quinns Rocks 6030"
                        });
                });

            modelBuilder.Entity("LeadManager.Models.Lead", b =>
                {
                    b.HasOne("Job", "Job")
                        .WithMany("Leads")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Job", b =>
                {
                    b.Navigation("Leads");
                });
#pragma warning restore 612, 618
        }
    }
}
